name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write # Grant permissions to create releases

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23' # Specify the Go version you are using
      # Install GoReleaser and run it
      - name: Configure git for private modules
        env:
            GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://x:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest # or specify a version like 'v1.19.2'
          args: release --clean # Providing args to run the release command
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for GoReleaser to create a release
